language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install sqlparse
  - pip install requests
  - pip install pyzipper
# command to run tests
script:
  - tests/test_packets.py